import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { FileKnowledgeRepository, HybridKnowledgeRetriever } from "../packages/knowledge/src/index.js";

type EvaluationQuestion = { id: string; user_question: string; expected_source: string | null; expected_topic: string; expected_answer_facts: string[]; unsupported: boolean };
const percentile = (values: number[], p: number) => { const sorted = [...values].sort((a, b) => a - b); if (!sorted.length) return 0; const index = (sorted.length - 1) * p; const lower = Math.floor(index); const upper = Math.ceil(index); return sorted[lower] + ((sorted[upper] - sorted[lower]) * (index - lower)); };
const root = resolve(process.cwd()); const processed = resolve(root, "data/processed/knowledge"); const evaluationDir = resolve(root, "data/evaluations/retrieval");
const repository = new FileKnowledgeRepository(resolve(processed, "documents.json"), resolve(processed, "chunks.json"));
let retriever: HybridKnowledgeRetriever; try { retriever = new HybridKnowledgeRetriever(repository.loadChunks()); } catch { console.error("Knowledge index unavailable. Run npm run kb:ingest first."); process.exit(1); }
const questions = JSON.parse(readFileSync(resolve(evaluationDir, "questions.json"), "utf8")) as EvaluationQuestion[]; const latencies: number[] = [];
const records = questions.map((question) => { const started = performance.now(); const response = retriever.search(question.user_question, { topK: 3, includeTrace: true }); const latency_ms = performance.now() - started; latencies.push(latency_ms); const ids = response.citations.map((citation) => citation.document_id); const correct = question.unsupported ? response.fallback : ids.includes(question.expected_source ?? ""); const verdict = correct ? "correct" : response.grounded ? "partial" : "incorrect"; return { ...question, retrieved_chunk_ids: response.results.map((result) => result.chunk.chunk_id), retrieved_document_ids: ids, relevance_explanation: question.unsupported ? (response.fallback ? "Safely rejected below the configured retrieval threshold." : "Unexpectedly retrieved grounded content.") : (correct ? "Expected source appears in returned citations." : "Expected source did not appear in returned citations."), verdict, latency_ms: Number(latency_ms.toFixed(3)), confidence: Number(response.confidence.toFixed(4)), fallback: response.fallback }; });
const supported = records.filter((record) => !record.unsupported); const metrics = { evaluation_size: records.length, top_1_accuracy: supported.filter((record) => record.retrieved_document_ids[0] === record.expected_source).length / supported.length, top_3_accuracy: supported.filter((record) => record.retrieved_document_ids.includes(record.expected_source ?? "")).length / supported.length, relevant_retrieval_rate: supported.filter((record) => record.verdict === "correct").length / supported.length, unsupported_query_rejection_rate: records.filter((record) => record.unsupported && record.fallback).length / records.filter((record) => record.unsupported).length, citation_coverage: supported.filter((record) => record.retrieved_document_ids.length > 0).length / supported.length, average_retrieval_latency_ms: Number((latencies.reduce((sum, value) => sum + value, 0) / latencies.length).toFixed(3)), p50_retrieval_latency_ms: Number(percentile(latencies, 0.5).toFixed(3)), p95_retrieval_latency_ms: Number(percentile(latencies, 0.95).toFixed(3)), adapter: "prototype/local-hashing-embedding-adapter", limitation: "Seven synthetic queries are a functional regression set, not a statistically meaningful production benchmark." };
mkdirSync(evaluationDir, { recursive: true }); writeFileSync(resolve(evaluationDir, "results.json"), `${JSON.stringify({ generated_at: new Date().toISOString(), records, metrics }, null, 2)}\n`);
console.log(JSON.stringify(metrics, null, 2));
